#!/bin/bash
read -p "If you want a full package install choose yes, otherwise choose no? (y/n) " yn

case $yn in
	y ) sudo pacman -S --noconfirm --needed - < pkglist_full;;
	n ) sudo pacman -S --noconfirm --needed - < pkglist_min;;
	* ) echo invalid response;
		continue;;
esac
