#!/bin/bash

yay -S zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-completions starship ttf-nerd-fonts-symbols-2048-em fzf find-the-command-git --needed --noconfirm
touch ~/.histfile
chsh -s /bin/zsh
