#!/bin/bash

read -p "If you want a full package install choose yes, choose no if you want a minimal, otherwise press enter.  (y/n) " yn

pkglist_full="micro
barrier
btop
man-db
bat
ncdu
duf
lazygit
ranger
ripgrep
neovim
xclip
fd
exa
ncdu
fzf
iotop
stress
conky
plank
cpupower
expac
baobab
gparted
kvantum-qt5
qt5ct
syncthing
dfc
snapper
arch-install-scripts
byobu
zoxide
diskus
dust
dua-cli
trash-cli
asp
tailscale
exfatprogs
stress
"

pkglist_min="micro
barrier
btop
bat
dua-cli
duf
fd
exa
lazygit
ranger
ripgrep
neovim
xsel
fd
zoxide
"

echo -e "$pkglist_full" > pkglist_full
echo -e "$pkglist_min" > pkglist_min

case $yn in
	y ) sudo pacman -S --noconfirm --needed - < pkglist_full;;
	n ) sudo pacman -S --noconfirm --needed - < pkglist_min;;
	* ) echo continue;;
esac

rm -rf pkglist_min pkglist_full
