#!/bin/bash
read -p "Do you want to install AUR packages (y/n) " yn

pkglist_aur="pacseek
nvm
icecream"
#macchina

echo -e "$pkglist_aur" > pkglist_aur

# mkdir -p ~/.build
# yay --builddir ~/.build --save
# yay -S --noconfirm --needed paru

case $yn in
	y )	yay -S --noconfirm --needed - < pkglist_aur;;
	* ) echo continue;;
esac

rm -rf pkglist_aur
