#!/bin/bash

yay -S zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-completions starship ttf-nerd-fonts-symbols fzf find-the-command-git --needed
touch ~/.histfile
chsh -s /bin/zsh
