#!/bin/bash

read -p "If you want a full package install choose yes, otherwise choose no? (y/n) " yn

case $yn in
	y ) yay -S --needed - < pkglist_full;;
	n ) yay -S --needed - < pkglist_min;;
	* ) echo invalid response;
		exit 1;;
esac
