#!/usr/bin/env python3

import argparse
import subprocess


def parse_function():
    parser = argparse.ArgumentParser(
        description="Function to mount a device for chroot"
    )
    parser.add_argument(
        "--filesystem",
        "-f",
        default="ext4",
        choices=["ext4", "btrfs"],
        help="Filesystem on the device ext4 or btrfs",
    )
    parser.add_argument(
        "--bootloader",
        "-b",
        default="BIOS",
        choices=["BIOS", "UEFI"],
        help="Boot partition type BIOS or UEFI",
    )

    args = parser.parse_args()

    return parser, args


def main():
    parser, args = parse_function()
    print("Argument values:")
    print(args.filesystem)
    print(args.bootloader)

    if args.bootloader == "UEFI":
        boot_dir = "MP/boot/efi"
    else:
        boot_dir = "MP/boot"
    subprocess.call(["umount", boot_dir])

    if args.filesystem == "ext4":
        subprocess.call(["umount", "MP"])
    elif args.filesystem == "btrfs":
        mtptt = ["/home", "/var/log", "/var/cache", ""]
        mtpts = ["MP" + x for x in mtptt]
        for i, (mtpt) in enumerate(mtpts):
            subprocess.call(["umount", mtpt])


if __name__ == "__main__":
    main()
