#!/bin/bash

_help() {
   # Display Help
   printf "\nHELP\n"
   printf "umount Image \n"
   printf "options:\n"
   printf "Either two options -f -b is required\n"
   printf "Or the single option -h\n\n"
   printf " -f  ext4 or btrfs\n"
   printf " -b  BIOS or UEFI\n"
   printf " -h  Print this Help.\n\n"
   printf "example:  umount-fun -f btrfs -b BIOS\n\n"
}

#################################################
##           start of script                   ##
#################################################

DEV=""
FS=""

# Available options
opt=":f:b:h"


while getopts "${opt}" arg; do
  case $arg in
    f)
      FS="${OPTARG}"
      ;;
    b)
      BL="${OPTARG}"
      ;;
    \?)
      echo "Option -${OPTARG} is not valid, aborting"
      exit 1
      ;;
    h|?)
      _help
      exit 1
      ;;
    :)
      echo "Option -${OPTARG} requires an argument, aborting"
      exit 1
      ;;
  esac
done




if [ "$FS" == "ext4" ]; then
   if [ "$BL" == "UEFI" ]; then
      umount MP/boot/efi
   else
      umount MP/boot
   fi
   umount MP
fi

if [ "$FS" == "btrfs" ]; then
   if [ "$BL" == "UEFI" ]; then
      umount MP/boot/efi
   else
      umount MP/boot
   fi
   umount MP/home MP/var/log MP/var/cache MP
fi


rm -rf MP
