#!/bin/bash

_help() {
   # Display Help
   printf "\nHELP\n"
   printf "Mount Image for Chroot\n"
   printf "options:\n"
   printf "Either three options -d -f -b are required\n"
   printf "Or the single option -h\n\n"
   printf " -d  enter device name\n"
   printf " -f  ext4 or btrfs\n"
   printf " -b  BIOS or UEFI\n"
   printf " -h  Print this Help.\n\n"
   printf "example:  mount-fun -d sda -f btrfs -b BIOS\n\n"
}

#################################################
##           start of script                   ##
#################################################

DEV=""
FS=""
BL=""

# Available options
opt=":d:f:b:h"


while getopts "${opt}" arg; do
  case $arg in
    d)
      DEV="/dev/${OPTARG}"
      ;;
    f)
      FS="${OPTARG}"
      ;;
    b)
      BL="${OPTARG}"
      ;;
    \?)
      echo "Option -${OPTARG} is not valid, aborting"
      exit 1
      ;;
    h|?)
      _help
      exit 1
      ;;
    :)
      echo "Option -${OPTARG} requires an argument, aborting"
      exit 1
      ;;
  esac
done

printf "\nDevice = $DEV"
printf "\nFile System = $FS\n"
# printf "\nDevice type = $BL\n"

DEV1="$DEV"1
DEV2="$DEV"2

mkdir -p MP

if [ "$FS" == "ext4" ]; then
   mount $DEV2 MP
   if [ "$BL" == "UEFI" ]; then
      mount $DEV1 MP/boot/efi
   else
      mount $DEV1 MP/boot
   fi
fi

if [ "$FS" == "btrfs" ]; then
   mount $DEV2 MP -o subvol=@
   mount $DEV2 MP/home -o subvol=@home
   mount $DEV2 MP/var/log -o subvol=@log
   mount $DEV2 MP/var/cache -o subvol=@cache
   if [ "$BL" == "UEFI" ]; then
      mount $DEV1 MP/boot/efi
   else
      mount $DEV1 MP/boot
   fi
fi
